#!/usr/bin/perl -w

use v5.34;
use utf8;

open DEPENDENCIES, ">>", "/tmp/chu-desk-dependencies";
open CUSTOM_DEPENDENCIES, ">>", "/tmp/chu-desk-custom-dependencies";

my $reading_dep = 0;
my $reading_custom_dep = 0;

while (<STDIN>) {
    if (/===DEPENDENCIES===/) {
        $reading_dep = 1;
	$reading_custom_dep = 0;
        next;
    }
    if (/===CUSTOM-DEPENDENCIES===/) {
        $reading_dep = 0;
        $reading_custom_dep = 1;
        next;
    }
    if ($reading_dep) {
        print DEPENDENCIES;
	next;
    }
    if ($reading_custom_dep) {
        print CUSTOM_DEPENDENCIES;
	next;
    }
    print;
}
