#!/bin/sh -e

OPTIND=1

verbose=0
alter="terminal"

while getopts "va:" opt; do
  case "$opt" in
    v) verbose=1 ;;
    a) alter=$OPTARG
  esac
done

shift $((OPTIND-1))

if [ $# -lt 1 ]; then
  echo "usage: install-conf [-v] [-a alter] directory [...]"
  exit 1
fi

# usage: install_file file
# Install a configuration to proper place according to its name.
# Every configuration will be preprocessed by m4.
install_file()
{
  file=$1

  flag=644
  case `basename $file` in
    *.sh) flag=755; suffix=.sh ;;
    *.py) flag=755; suffix=.py ;;
  esac
  tmpfile=/tmp/`basename $file $suffix`

  file_path=`path-of $tmpfile`

  [ $verbose -eq 1 ] && echo "Installing $file to $file_path (alter: $alter)"

  [ ! -f "$tmpfile" -o $file -nt $tmpfile ] &&
    echo "chu_desk_dependencies" \
      | m4 -P -DCHU_DESK_ALTER=$alter include.m4 $file - \
      | extract-dep > $tmpfile

  case `basename $file` in
    HOME*|CTX* ) install -C -m $flag $tmpfile $file_path ;;
    * ) sudo install -C -m $flag $tmpfile $file_path ;;
  esac

  rm $tmpfile

  unset file
  unset file_path
  unset tmpfile
  unset flag
  unset suffix
}

# usage: install_directory directory
# Install the contents of the directory to proper place according to its name.
# All files will be preprocessed by m4.
# Sub directories are not allowed.
install_directory()
{
  directory=$1
  directory_path=`path-of $1`

  [ -d $directory_path ] || mkdir -p $directory_path

  for f in `ls -a $directory`; do
    tf=`basename $f`
    tf=`name-of $directory_path/$tf`
    [ -f $directory/$f ] && cp $directory/$f $tf && install_file $tf && rm $tf
  done

  unset directory
  unset directory_path
}

while [ $# -ne 0 ]; do
  if [ -d $1 ]; then
    for f in $1/*--*; do
      if [ -d $f ]; then
        install_directory $f
      else
        install_file $f
      fi
    done
  else
    echo "There's no directory named $1"
    exit 1
  fi
  shift 1
done
