#!/bin/bash -e

OPTIND=1

verbose=0
alter="terminal"

while getopts "va:" opt; do
  case "$opt" in
    v) verbose=1 ;;
    a) alter=$OPTARG
  esac
done

shift $((OPTIND-1))

if [ $# -lt 1 ]; then
  echo "usage: install-conf [-v] [-a alter] directory [...]"
  exit 1
fi

# usage: install_file file
# Install a configuration to proper place according to its name.
# Every configuration will be preprocessed by m4.
install_file()
{
  file=$1

  flag=644
  tmpfile=/tmp/`basename $file`
  file_path=`path-of $file`

  [ $verbose -eq 1 ] && echo "Installing $file to $file_path (alter: $alter)"

  [ -f "$tmpfile" ] && sudo rm "$tmpfile"
  echo "chu_desk_dependencies" \
    | m4 -P -DCHU_DESK_ALTER=$alter include.m4 "$file" - \
    | extract-dep > "$tmpfile"

  mkdir -p `dirname "$file_path"`
  case `basename "$file"` in
    HOME* ) install -C -m $flag "$tmpfile" "$file_path" ;;
    * ) sudo install -C -m $flag "$tmpfile" "$file_path" ;;
  esac

  unset file
  unset file_path
  unset tmpfile
  unset flag
}

sudo rm -f /tmp/chu-desk-dependencies

while [ $# -ne 0 ]; do
  if [ -d $1 ]; then
    for f in $1/{ETC,HOME}--*; do
      if [ -f $f ]; then
        install_file $f
      fi
    done
  else
    echo "There's no directory named $1"
    exit 1
  fi
  shift 1
done
