# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black-pre-commit-mirror.git
    rev: 24.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
-   repo: local
    hooks:
    -   id: test
        name: run tests
        entry: make test
        language: system
        pass_filenames: false
    -   id: jsonnetfmt
        name: run formatter for jsonnet files
        entry: jsonnetfmt -i
        language: system
        files: '(.+\.libsonnet)|(.+\.jsonnet)'
