[build-system]
requires = ['setuptools>=66', 'setuptools-scm>=8.0']
build-backend = 'setuptools.build_meta'

[project]
name = ''
description = ""
requires-python = '>=3.11'
dependencies = [
]
dynamic = ['version']

[tool.setuptools_scm]
